dashbot/urls.py
from django.conf.urls import url, include
from django.contrib import admin
from dashboard import views as dashboard_views
from estadisticas import views as estadisticas_views
from usuarios import views as usuarios_views
from admin1 import views as admin1_views
from admin2 import views as admin2_views
from django.conf.urls.static import static
from django.conf import settings
from django.contrib.auth.views import password_reset, password_reset_done, password_reset_confirm, password_reset_complete
import notifications.urls

# urls de app dashboard
extra_patterns1 = [
    url(r'^login', dashboard_views.login_view, name = 'login'),
    url(r'^logout/$', dashboard_views.login_out, name = 'logout'),
    url(r'^home/$', dashboard_views.home, name = 'home'),
    url(r'^agentes/(?P<id_cliente>[-A-Za-z0-9_]+)$', dashboard_views.listar_agentes, name = 'agentes'),
    url(r'^interacciones/(?P<id_agente>[-A-Za-z0-9_]+)$', dashboard_views.listar_interacciones, name = 'interacciones'),
    url(r'^base/(?P<id_agente>[-A-Za-z0-9_]+)/(?P<source>[-A-Za-z0-9_]+)$', dashboard_views.interacciones_source, name = 'base'),
    url(r'^get_request_detail$', dashboard_views.get_request_detail, name = 'get_request_detail'),
    url(r'^activar/$', dashboard_views.activar, name = 'activar'),
    url(r'^eliminar_notificacion3/(?P<id_ses>[-A-Za-z0-9_]+)/(?P<id_plat>[-A-Za-z0-9_]+)/(?P<id_not>[-A-Za-z0-9_]+)$', dashboard_views.eliminar_notificacion3, name='eliminar_notificacion3'),
    url(r'^eliminar_notificacion2/(?P<id_cita>[-A-Za-z0-9_]+)$', dashboard_views.eliminar_notificacion2, name='eliminar_notificacion2'),
    url(r'^eliminar_notificacion5/(?P<id_cita>[-A-Za-z0-9_]+)$', dashboard_views.eliminar_notificacion5, name='eliminar_notificacion5'),
    url(r'^eliminar_notificacion4/(?P<id_not>[-A-Za-z0-9_]+)/(?P<id_ses>[-A-Za-z0-9_]+)$', dashboard_views.eliminar_notificacion4, name='eliminar_notificacion4'),
    url(r'^sesiones/(?P<id_agente>[-A-Za-z0-9_]+)/(?P<source>[-A-Za-z0-9_]+)$', dashboard_views.sesiones, name = 'sesiones'),
    url(r'^timeline/(?P<id_agente>[-A-Za-z0-9_]+)/(?P<source>[-A-Za-z0-9_]+)/(?P<session>[-A-Za-z0-9_]+)$', dashboard_views.timeline, name = 'timeline'),
    url(r'^timelinePDF/(?P<id_agente>[-A-Za-z0-9_]+)/(?P<source>[-A-Za-z0-9_]+)/(?P<session>[-A-Za-z0-9_]+)$', dashboard_views.timelinePDF, name = 'timelinePDF'),
    url(r'^facebook_room/(?P<id_agente>[-A-Za-z0-9_]+)/(?P<source>[-A-Za-z0-9_]+)/(?P<session>[-A-Za-z0-9_]+)/(?P<chat_id>[-A-Za-z0-9_]+)$', dashboard_views.facebook_room, name = 'facebook_room'),
    url(r'^telegram_room/(?P<id_agente>[-A-Za-z0-9_]+)/(?P<source>[-A-Za-z0-9_]+)/(?P<session>[-A-Za-z0-9_]+)/(?P<chat_id>[-A-Za-z0-9_]+)$', dashboard_views.telegram_room, name = 'telegram_room'),
    url(r'^whatsapp_room/(?P<id_agente>[-A-Za-z0-9_]+)/(?P<source>[-A-Za-z0-9_]+)/(?P<session>[-A-Za-z0-9_]+)$', dashboard_views.whatsapp_room, name = 'whatsapp_room'),
    url(r'^ajax/cambiar_sesion_status_on_close/$', dashboard_views.cambiar_sesion_status_on_close, name='sesion_status'),
    url(r'^ajax/cambiar_sesion_status_on_enter/$', dashboard_views.cambiar_sesion_status_on_enter, name='sesion_status_enter'),
    url(r'^ajax/eliminar_notificacion/$', dashboard_views.eliminar_notificacion, name='eliminar_notificacion'),
    url(r'^ajax/contador_interacciones/$', dashboard_views.contador_interacciones, name='contador_interacciones'),
    url(r'^ajax/contador_sesiones/$', dashboard_views.contador_sesiones, name='contador_sesiones'),
    url(r'^ajax/borrar_registro_interacciones_realtime/$', dashboard_views.borrar_registro_interacciones_realtime, name='borrar_registro_interacciones_realtime'),
    url(r'^notificaciones/$', dashboard_views.notificaciones, name = 'notificaciones'),
    url(r'^getDataTableInfoRealTime/(?P<id_agente>[-A-Za-z0-9_]+)/(?P<source>[-A-Za-z0-9_]+)/(?P<session>[-A-Za-z0-9_]+)$', dashboard_views.getDataTableInfoRealTime, name = 'getDataTableInfoRealTime'),
    url(r'^send_message$', dashboard_views.send_message, name = 'send_message'),
    url(r'^send_session$', dashboard_views.send_session, name = 'send_session'),
    url(r'^imput_message$', dashboard_views.imput_message, name = 'imput_message'),
    url(r'^chats/(?P<agente>[-A-Za-z0-9_]+)/(?P<id_sesion>[-A-Za-z0-9_]+)$', dashboard_views.chats, name = 'chats'),
    url(r'^cita_resuelta/(?P<id_cita>[-A-Za-z0-9_]+)$', dashboard_views.cita_resuelta, name = 'cita_resuelta'),
    url(r'^webchat_room/(?P<id_agente>[-A-Za-z0-9_]+)/(?P<source>[-A-Za-z0-9_]+)/(?P<session>[-A-Za-z0-9_]+)$', dashboard_views.webchat_room, name = 'webchat_room'),
]+ static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

# urls de app estadisticas
extra_patterns2 = [
    url(r'^entradas_utilizadas/(?P<id_agente>[-A-Za-z0-9_]+)$', estadisticas_views.entradas_utilizadas, name = 'entradas_utilizadas'),
    url(r'^frases_erroneas/(?P<id_agente>[-A-Za-z0-9_]+)$', estadisticas_views.frases_erroneas, name = 'frases_erroneas'),
    url(r'^interacciones_hora/(?P<id_agente>[-A-Za-z0-9_]+)$', estadisticas_views.interacciones_hora, name = 'interacciones_hora'),
    url(r'^interacciones_fecha/(?P<id_agente>[-A-Za-z0-9_]+)$', estadisticas_views.interacciones_fecha, name = 'interacciones_fecha'),
    url(r'^sesiones_fecha/(?P<id_agente>[-A-Za-z0-9_]+)$', estadisticas_views.sesiones_fecha, name = 'sesiones_fecha'),
    url(r'^estadisticas_personalizadas/$', estadisticas_views.graficas_personalizadas, name = 'graficas_personalizadas'),
]+ static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

# urls de app usuarios
extra_patterns3 = [
    url(r'^modificar_perfil/(?P<id_usuario>[-A-Za-z0-9_]+)$', usuarios_views.modificar_perfil, name = 'modificar_perfil'),
    url(r'^operadores/$', usuarios_views.empleados, name='operadores'),
    url(r'^faq/$', usuarios_views.faq, name='faq'),
    url(r'^bots_afiliados/(?P<id_usuario>[-A-Za-z0-9_]+)$', usuarios_views.bots_afiliados, name='bots_afiliados'),
    url(r'^modificar_bots_afiliados/(?P<id_usuario>[-A-Za-z0-9_]+)/(?P<id_bot>[-A-Za-z0-9_]+)$', usuarios_views.modificar_bots_afiliados, name='modificar_bots_afiliados'),
    url(r'^perfil/(?P<id_usuario>[-A-Za-z0-9_]+)$', usuarios_views.perfil, name = 'perfil'),
]+ static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

# urls de app admin1
extra_patterns4 = [
    url(r'^ingresar_cliente/$', admin1_views.ingresar_cliente, name='ingresar_cliente'),
    url(r'^ingresar_agente/$', admin1_views.ingresar_agente, name='ingresar_agente'),
    url(r'^ingresar_usuario/$', admin1_views.ingresar_usuario, name='ingresar_usuario'),
    url(r'^borrar_sesiones/$', admin1_views.borrar_sesiones_plataforma, name='borrar_sesiones'),
    url(r'^ingresar_grafica/$', admin1_views.ingresar_grafica, name='ingresar_grafica'),
    url(r'^asignar_grafica/(?P<id_cliente>[-A-Za-z0-9_]+)/$', admin1_views.asignar_grafica, name='asignar_grafica'),
    url(r'^agregar_graficas/(?P<id_cliente>[-A-Za-z0-9_]+)/(?P<id_grafica>[-A-Za-z0-9_]+)/$', admin1_views.agregar_graficas, name='agregar_graficas'),
]+ static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

# urls de app admin2
extra_patterns5 = [
    url(r'^equipos_agente/$', admin2_views.equipos_agente, name='equipos_agente'),
    url(r'^equipos_agenteusuarios/(?P<id_agente>[-A-Za-z0-9_]+)$', admin2_views.equipos_agenteusuarios, name='equipos_agenteusuarios'),
    url(r'^ingresar_operador/$', admin2_views.ingresar_operador, name='ingresar_operador'),
    url(r'^ajax/asignar_bot/$', admin2_views.asignar_bot, name='asignar_bot'),
    url(r'^ajax/desvincular_bot/$', admin2_views.desvincular_bot, name='desvincular_bot'),
]+ static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

# urls para Recuperar contraseña
extra_patterns6 = [
    url(r'^reset/password_reset/$', password_reset,
        {'template_name':'registration/password_reset_form.html',
        'email_template_name':'registration/password_reset_email.html'},
        name='password_reset'),
    url(r'^reset/password_reset_done/$', password_reset_done,
        {'template_name':'registration/password_reset_done.html'},
        name='password_reset_done'),
    url(r'^reset/(?P<uidb64>[-A-Za-z0-9_]+)/(?P<token>.+)$', password_reset_confirm,
        {'template_name':'registration/password_reset_confirm.html'},
        name='password_reset_confirm'),
    url(r'^reset/done/$', password_reset_complete,
        {'template_name':'registration/password_reset_complete.html'},
        name='password_reset_complete'),
]+ static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

# urls generales
urlpatterns = [
    url(r'^$', dashboard_views.index, name='index'),
    url(r'^admin/', admin.site.urls),
    url('^inbox/notifications/', include(notifications.urls, namespace='notifications')),
    url(r'^', include(extra_patterns1)),
    url(r'^', include(extra_patterns2)),
    url(r'^', include(extra_patterns3)),
    url(r'^', include(extra_patterns4)),
    url(r'^', include(extra_patterns5)),
    url(r'^', include(extra_patterns6)),
]+ static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

admin2/models.py
from django.db import models

# Create your models here.

admin2/forms.py
from django import forms
from usuarios.models import *
from django.contrib.admin import widgets 
from django.core.files import File
from django.contrib.auth.models import *
from dashboard.models import *
from usuarios.models import *
from django.db import IntegrityError
from django.contrib.auth.models import User
from django.forms import ModelChoiceField, ModelMultipleChoiceField

class UserFormOperador(forms.Form):

    username = forms.CharField(label = "Usuario",max_length=50,min_length=3 ,required = True, widget = forms.TextInput(attrs={'class': 'form-control', 'placeholder': 'Usuario'}))
    email = forms.EmailField(label = "Correo electrónico", required = True, widget = forms.EmailInput(attrs={'class': 'form-control', 'placeholder': 'Correo electrónico'}))
    nombres = forms.CharField(label = "Nombre", required = True, widget = forms.TextInput(attrs={'class': 'form-control', 'placeholder': 'Nombre del usuario'}))
    apellido_paterno = forms.CharField(label = "Apellido Paterno", required = True, widget = forms.TextInput(attrs={'class': 'form-control', 'placeholder': 'Apellido Paterno'}))
    apellido_materno = forms.CharField(label = "Apellido Materno", required = True, widget = forms.TextInput(attrs={'class': 'form-control', 'placeholder': 'Apellido Materno'}))
    def __init__(self, *args, **kwargs):
        super(UserFormOperador, self).__init__(*args, **kwargs)
        # Errores predeterminados definidos en el modelo este disparará errores para campo requerido, unico, invalido y con caracterers faltantes
        for field in self.fields.values():
            field.error_messages = {'required':'Ingrese {fieldname}'.format(
                fieldname=field.label), 'unique':'{fieldname} registrado en el sistema'.format(
                fieldname=field.label), 'invalid':'Valor Inválido'.format(
                fieldname=field.label), 'min_length':'Realice completacion de campo {fieldname}'.format(
                fieldname=field.label)}


class UsuarioAgenteForm(forms.Form):

    agente = forms.CharField()

    def __init__(self, *args, **kwargs):
        self.user = kwargs.pop('user')
        super(UsuarioAgenteForm, self).__init__(*args, **kwargs)
        
        # AQUÍ ESTÁ EL USUARIO
        # print(self.user)

        usuario = self.user
        usuarioExt = Usuario.objects.get(user=usuario)
        cliente = Cliente.objects.get(nombre_cliente=usuarioExt.cliente)

        self.fields['agente'] = forms.ModelMultipleChoiceField(label = 'Bots disponibles', required = False, queryset=Agente.objects.filter(cliente=cliente), widget = forms.CheckboxSelectMultiple())

        for field in self.fields.values():
            field.error_messages = {'required':'Ingrese {fieldname}'.format(
                fieldname=field.label), 'unique':'{fieldname} registrado en el sistema'.format(
                fieldname=field.label), 'invalid':'Valor Inválido'.format(
                fieldname=field.label), 'min_length':'Realice completacion de campo {fieldname}'.format(
                fieldname=field.label)}
                
        for campos in self.fields:
            self.fields[campos].widget.attrs.update({'class': 'form-control'})
            self.fields['agente'].widget.attrs["class"] = 'i-checks'

templates/admin2/ingresar_operador.html
{% extends 'tags/empty_page.html' %}
{% load staticfiles %}
{% load querys %}

{% block head %}

    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">

    <title>

        {% if datos_empresa.nombre_empresa == None %}
          Dashboard | Bienvenido
        {% else %}
          {{datos_empresa.nombre_empresa}} | Bienvenido
        {% endif %}

    </title>

    <link rel="icon" type="image/png" href="{% static 'img/icono-springlabs.png' %}" />

    <link href="{% static 'css/bootstrap.min.css' %}" rel="stylesheet">

    <link href="{% static 'font-awesome/css/font-awesome.css' %}" rel="stylesheet">

    <link href="{% static 'css/plugins/iCheck/custom.css' %}" rel="stylesheet">

    <link href="{% static 'css/plugins/chosen/bootstrap-chosen.css' %}" rel="stylesheet">

    <link href="{% static 'css/plugins/bootstrap-tagsinput/bootstrap-tagsinput.css' %}" rel="stylesheet">

    <link href="{% static 'css/plugins/awesome-bootstrap-checkbox/awesome-bootstrap-checkbox.css' %}" rel="stylesheet">

    <link href="{% static 'css/plugins/steps/jquery.steps.css' %}" rel="stylesheet">

    <link href="{% static 'css/animate.css' %}" rel="stylesheet">

    <link href="{% static 'css/style.css' %}" rel="stylesheet">

    <link href="{% static 'css/estilos_menu.css' %}" rel="stylesheet">
    <script type="text/javascript" src="{% static 'js/menu.js' %}"></script>


{% endblock head %}

{% block js %}
    <!-- Mainly scripts -->
    <script src="{% static 'js/jquery-3.1.1.min.js' %}"></script>
    <script src="{% static 'js/bootstrap.min.js' %}"></script>

    <!-- Custom and plugin javascript -->
    <script src="{% static 'js/inspinia.js' %}"></script>
    <script src="{% static 'js/plugins/pace/pace.min.js' %}"></script>
    <script src="{% static 'js/plugins/slimscroll/jquery.slimscroll.min.js' %}"></script>

   <!-- Input Mask-->
    <script src="{% static 'js/plugins/jasny/jasny-bootstrap.min.js' %}"></script>

    <script src="{% static 'js/plugins/ionRangeSlider/ion.rangeSlider.min.js' %}"></script>

    <!-- iCheck -->
    <script src="{% static 'js/plugins/iCheck/icheck.min.js' %}"></script>

    <!-- MENU -->
    <script src="{% static 'js/plugins/metisMenu/jquery.metisMenu.js' %}"></script>

    <script src="{% static 'js/plugins/dataTables/datatables.min.js' %}"></script>

    <!-- Steps -->
    <script src="{% static 'js/plugins/steps/jquery.steps.min.js' %}"></script>

    <!-- Jquery Validate -->
    <script src="{% static 'js/plugins/validate/jquery.validate.min.js' %}"></script>

    <link href="{% static 'css/plugins/dataTables/datatables.min.css' %}" rel="stylesheet">


{% endblock js %}

{% block scripts %}
    <script>
        $(document).ready(function(){
            $('.dataTables-example').DataTable({
                pageLength: 25,
                responsive: true,
                dom: '<"html5buttons"B>lTfgitp',
                buttons: [
                    { extend: 'copy'},
                    {extend: 'csv'},
                    {extend: 'excel', title: 'ExampleFile'},
                    {extend: 'pdf', title: 'ExampleFile'},

                    {extend: 'print',
                     customize: function (win){
                            $(win.document.body).addClass('white-bg');
                            $(win.document.body).css('font-size', '10px');

                            $(win.document.body).find('table')
                                    .addClass('compact')
                                    .css('font-size', 'inherit');
                    }
                    }
                ]

            });

        });
    </script>
<script>
        $(document).ready(function(){
            $("#wizard").steps();
            $("#form").steps({
                bodyTag: "fieldset",
                onStepChanging: function (event, currentIndex, newIndex)
                {
                    // Always allow going backward even if the current step contains invalid fields!
                    if (currentIndex > newIndex)
                    {
                        return true;
                    }

                    // Forbid suppressing "Warning" step if the user is to young
                    if (newIndex === 3 && Number($("#age").val()) < 18)
                    {
                        return false;
                    }

                    var form = $(this);

                    // Clean up if user went backward before
                    if (currentIndex < newIndex)
                    {
                        // To remove error styles
                        $(".body:eq(" + newIndex + ") label.error", form).remove();
                        $(".body:eq(" + newIndex + ") .error", form).removeClass("error");
                    }

                    // Disable validation on fields that are disabled or hidden.
                    form.validate().settings.ignore = ":disabled,:hidden";

                    // Start validation; Prevent going forward if false
                    return form.valid();
                },
                onStepChanged: function (event, currentIndex, priorIndex)
                {
                    // Suppress (skip) "Warning" step if the user is old enough.
                    if (currentIndex === 2 && Number($("#age").val()) >= 18)
                    {
                        $(this).steps("next");
                    }

                    // Suppress (skip) "Warning" step if the user is old enough and wants to the previous step.
                    if (currentIndex === 2 && priorIndex === 3)
                    {
                        $(this).steps("previous");
                    }
                },
                onFinishing: function (event, currentIndex)
                {
                    var form = $(this);

                    // Disable validation on fields that are disabled.
                    // At this point it's recommended to do an overall check (mean ignoring only disabled fields)
                    form.validate().settings.ignore = ":disabled";

                    // Start validation; Prevent form submission if false
                    return form.valid();
                },
                onFinished: function (event, currentIndex)
                {
                    var form = $(this);

                    // Submit form input
                    form.submit();
                }
            }).validate({
                        errorPlacement: function (error, element)
                        {
                            element.before(error);
                        },
                        rules: {
                            confirm: {
                                equalTo: "#password"
                            }
                        }
                    });


            $('#id_username').keypress(function(e) {
                preventNumberInput(e);
            });

            $('#id_nombres').keypress(function(e) {
                preventNumberInput(e);
            });

            $('#id_apellido_paterno').keypress(function(e) {
                preventNumberInput(e);
            });
            $('#id_apellido_materno').keypress(function(e) {
                preventNumberInput(e);
            });

            $('#id_email').keypress(function(e) {
                preventRareData(e);
            });

       });

        function preventNumberInput(e){
            var keyCode = (e.keyCode ? e.keyCode : e.which);
            if (keyCode > 47 && keyCode < 58){
                e.preventDefault();
            }
        }

        function preventRareData(e){
            var forbidden = [123,124,125,126,91,92,93,94,96,58,59,60,61,62,63,47,43,42,41,40,33,34,35,36,37,38,39,192,63,191];
            var keyCode = (e.keyCode ? e.keyCode : e.which);
            console.log(keyCode);
            if (!forbidden.indexOf(keyCode)){
                e.preventDefault();
            }
        }
    </script>



{% endblock scripts %}

{% block contenido_header %}

    <div class="row wrapper white-bg page-heading">
        <div class="col-sm-4">
            <h2><img alt="image" height="50" src="{{cliente.logotipo.url}}" /></h2>
            <ol class="breadcrumb">
                <li>
                    <a href="{% url 'home' %}">Inicio</a>
                </li>
                <li class="active">
                    <a href=""><strong>Ingresar Operador</strong></a>
                </li>
            </ol>
        </div>
        <div class="col-sm-8">
            <div class="title-action">
                <h2><strong>{{cliente.nombre_cliente}}</strong></h2>
            </div>
        </div>
    </div>
{% endblock contenido_header %}

{% block contenido %}
    {% if request.user|has_group:"Cliente Administrador" %}
        <div class="wrapper wrapper-content animated fadeInRight">
            <div class="row">
                <div class="col-md-1"></div>
                <div class="col-lg-10">
                    {% if mensaje_error %}
                        <div class="alert alert-danger">
                            El nombre de usuario ya existe, favor asigne un nombre de usuario diferente.
                        </div>
                    {% endif %}
                    {% if mensaje_exito %}
                        <div class="alert alert-success">
                            El usuario se registró de manera exitosa.
                        </div>
                    {% endif %}
                    <div class="ibox">
                        <div class="ibox-content content-grafica">
                            <h5 class="text-titulo">Ingresar Usuario</h5>
                            <p>
                                Completa los campos para agregar un nuevo usuario.
                            </p>
                            <form id="form" action="" class="wizard-big" method="post" role="form" enctype="multipart/form-data">
                                <h1>Ingresar Usuario</h1>
                                <fieldset>
                                    {% csrf_token %}
                                    {{ operador.as_p }}
                                </fieldset>
                                <h1>Asignar Bots</h1>
                                <fieldset>
                                    <h2>Asignar bots a usuario</h2>
                                    {% csrf_token %}
                                    {{ usuarioAgente.as_p }}
                                </fieldset>
                            </form>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    {% endif %}
{% endblock contenido %}